export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';


export const FETCH_ALL_BAGS_START = 'FETCH_ALL_BAGS_START';
export const FETCH_ALL_BAGS_SUCCESS = 'FETCH_ALL_BAGS_SUCCESS';
export const FETCH_ALL_BAGS_FAIL = 'FETCH_ALL_BAGS_FAIL';

export const FETCH_SELECTED_BAGS_BY_CATEGORY_START = 'FETCH_SELECTED_BAGS_BY_CATEGORY_START';
export const FETCH_SELECTED_BAGS_BY_CATEGORY_SUCCESS = 'FETCH_SELECTED_BAGS_BY_CATEGORY_SUCCESS';
export const FETCH_SELECTED_BAGS_BY_CATEGORY_FAIL = 'FETCH_SELECTED_BAGS_BY_CATEGORY_FAIL';

export const FETCH_SELECTED_BAGS_BY_BRAND_START = 'FETCH_SELECTED_BAGS_BY_BRAND_START';
export const FETCH_SELECTED_BAGS_BY_BRAND_SUCCESS = 'FETCH_SELECTED_BAGS_BY_BRAND_SUCCESS';
export const FETCH_SELECTED_BAGS_BY_BRAND_FAIL = 'FETCH_SELECTED_BAGS_BY_BRAND_FAIL';

export const FETCH_BAG_Details_START = 'FETCH_BAG_Details_START';
export const FETCH_BAG_Details_SUCCESS = 'FETCH_BAG_Details_SUCCESS';
export const FETCH_BAG_Details_FAIL = 'FETCH_BAG_Details_FAIL';


export const FETCH_BAG_ORDERS_START = 'FETCH_BAG_ORDERS_START';
export const FETCH_BAG_ORDERS_SUCCESS = 'FETCH_BAG_ORDERS_SUCCESS';
export const FETCH_BAG_ORDERS_FAIL = 'FETCH_BAG_ORDERS_FAIL';
export const ADD_ORDER_START = 'ADD_ORDER_START';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';

export const FETCH_BAG_REVIEWS_START = 'FETCH_BAG_REVIEWS_START';
export const FETCH_BAG_REVIEWS_SUCCESS = 'FETCH_BAG_REVIEWS_SUCCESS';
export const FETCH_BAG_REVIEWS_FAIL = 'FETCH_BAG_REVIEWS_FAIL';

export const ADD_REVIEW_START = 'ADD_REVIEW_START';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

export const UPDATE_REVIEW_START = 'UPDATE_REVIEW_START';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';

export const ADD_RATING_START = 'ADD_RATING_START';
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS';
export const ADD_RATING_FAIL = 'ADD_RATING_FAIL';

export const UPDATE_RATING_START = 'UPDATE_RATING_START';
export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
export const UPDATE_RATING_FAIL = 'UPDATE_RATING_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_CART_DRAWER = 'SHOW_CART_DRAWER';

export const SET_CURRENT_COVER_IMG = 'SET_CURRENT_COVER_IMG';

export const SET_ITEMS_LIST_DEFAULT_FILTER = 'SET_ITEMS_LIST_DEFAULT_FILTER';